// Copyright © 2023 Intel Corporation. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ControllerBoard is an autogenerated mock type for the ControllerBoard type
type ControllerBoard struct {
	mock.Mock
}

// GetStatus provides a mock function with given fields:
func (_m *ControllerBoard) GetStatus() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Read provides a mock function with given fields:
func (_m *ControllerBoard) Read() {
	_m.Called()
}

// Write provides a mock function with given fields: _a0
func (_m *ControllerBoard) Write(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
